sudo: required

services:
  - docker

language: generic

env:
- DISTRI=ubuntu DESKTOP=xfce
- DISTRI=ubuntu DESKTOP=icewm
- DISTRI=centos DESKTOP=xfce
- DISTRI=centos DESKTOP=icewm

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - bash travis/build-images.sh ${DISTRI} ${DESKTOP}
after_success:
  - bash travis/push-images.sh ${DISTRI} ${DESKTOP}
